import express from 'express'; import crypto from 'crypto'; import webpush from 'web-push';
const app=express(); app.use(express.json({limit:'100kb'})); app.use(express.static('public'));
const PORT=process.env.PORT||3000; const PUB=process.env.VAPID_PUBLIC_KEY, PRIV=process.env.VAPID_PRIVATE_KEY;
if(PUB&&PRIV) webpush.setVapidDetails(process.env.VAPID_SUBJECT||'mailto:admin@example.com',PUB,PRIV);
const watches=new Map(); const SYMBOLS=(process.env.SCAN_SYMBOLS||'BTCUSDT,ETHUSDT,SOLUSDT,BNBUSDT,XRPUSDT,DOGEUSDT,ADAUSDT,LINKUSDT,AVAXUSDT,SUIUSDT,ONDOUSDT').split(',');
async function j(path){const r=await fetch(`https://fapi.binance.com${path}`); if(!r.ok)throw new Error(`Binance ${r.status}`); return r.json()}
async function klines(s,i='1h',l=80){return j(`/fapi/v1/klines?symbol=${s}&interval=${i}&limit=${l}`)}
const avg=a=>a.reduce((x,y)=>x+y,0)/a.length; const ema=(v,n)=>{let k=2/(n+1),e=v[0];for(const x of v.slice(1))e=x*k+e*(1-k);return e};
function atr(k,n=14){const x=k.slice(-(n+1)),tr=[];for(let i=1;i<x.length;i++){const h=+x[i][2],l=+x[i][3],pc=+x[i-1][4];tr.push(Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc)))}return avg(tr)}
function build(symbol,k,capital){const closed=k.slice(0,-1),c=closed.map(x=>+x[4]),v=closed.map(x=>+x[5]);if(c.length<55)return null;const p=c.at(-1),e20=ema(c.slice(-50),20),e50=ema(c.slice(-70),50),a=atr(closed),vr=v.at(-1)/avg(v.slice(-21,-1)),trend=Math.abs(e20-e50)/p;let side,score;if(e20>e50&&p>e20){side='LONG';score=trend*800+Math.min(vr,2)*1.2}else if(e20<e50&&p<e20){side='SHORT';score=trend*800+Math.min(vr,2)*1.2}else return null;if(vr<.75)return null;const entry=p,stop=side==='LONG'?entry-1.15*a:entry+1.15*a,riskPct=Math.abs(entry-stop)/entry;if(riskPct<.004||riskPct>.04)return null;const risk=Math.min(capital*.02,2),lev=Math.min(5,Math.max(2,Math.floor(.06/riskPct))),notional=risk/riskPct,margin=Math.min(notional/lev,capital*.35),actual=margin*lev,qty=actual/entry,maxLoss=Math.abs(entry-stop)*qty,tp1=side==='LONG'?entry+1.5*Math.abs(entry-stop):entry-1.5*Math.abs(entry-stop),tp2=side==='LONG'?entry+2.5*Math.abs(entry-stop):entry-2.5*Math.abs(entry-stop);return{id:crypto.randomUUID(),symbol,side,leverage:lev,capital,margin:+margin.toFixed(2),entry:+entry.toPrecision(7),stop:+stop.toPrecision(7),tp1:+tp1.toPrecision(7),tp2:+tp2.toPrecision(7),maxLoss:+maxLoss.toFixed(2),profit1:+(Math.abs(tp1-entry)*qty).toFixed(2),profit2:+(Math.abs(tp2-entry)*qty).toFixed(2),score:+score.toFixed(2),reason:`1H EMA20/50 + hacim ${vr.toFixed(2)}x + ATR stop`}}
async function best(capital){const a=await Promise.all(SYMBOLS.map(async s=>{try{return build(s,await klines(s),capital)}catch{return null}}));return a.filter(Boolean).sort((x,y)=>y.score-x.score)[0]||null}
async function valid(s){const k=await klines(s.symbol),n=build(s.symbol,k,s.capital);if(!n||n.side!==s.side)return false;const p=+k.at(-1)[4];return Math.abs(p-s.entry)/s.entry<=.004&&n.score>=Math.max(1,s.score*.75)}
app.get('/api/config',(_,r)=>r.json({vapidPublicKey:PUB||''}));
app.post('/api/setup',async(q,r)=>{try{const capital=Math.max(10,Math.min(100000,+q.body.capital||100)),s=await best(capital);if(!s)return r.status(404).json({error:'Şu an temiz setup yok. Bekle.'});r.json(s)}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/watch',(q,r)=>{const {subscription,setup}=q.body||{};if(!subscription?.endpoint||!setup?.symbol)return r.status(400).json({error:'Bildirim aboneliği veya setup eksik'});watches.set(subscription.endpoint,{subscription,setup,armedAt:Date.now()});r.json({ok:true})});
app.post('/api/watch/disarm',(q,r)=>{if(q.body?.endpoint)watches.delete(q.body.endpoint);r.json({ok:true})});
async function poll(){for(const [id,w] of [...watches])try{if(await valid(w.setup)){const s=w.setup;await webpush.sendNotification(w.subscription,JSON.stringify({title:`İŞLEME GİR — ${s.symbol} ${s.side}`,body:`${s.leverage}x • Giriş ~${s.entry} • Stop ${s.stop} • Kayıp ~$${s.maxLoss} • TP1 ${s.tp1} (+$${s.profit1}) • TP2 ${s.tp2} (+$${s.profit2})`,url:'/'}));watches.delete(id)}}catch(e){if(e.statusCode===404||e.statusCode===410)watches.delete(id);console.error(e.message)}}
setInterval(poll,60000); app.listen(PORT,()=>console.log(`TradeAlarm PWA :${PORT}`));
